### ISSUE TITLE
Not compatible with the latest version of serverless

### ISSUE THREAD

**Issue by OneMuppet** [joostfarla/serverless-cors-plugin#5]
There are lot's of breaking changes in the new version of serverless released yesterday which is what is causing this. 

Maybe the CORS-functionality in this plugin could be achieved with the new templates introduced in serverless 0.1.0?

https://github.com/serverless/serverless/releases

```javascript
/User/X/.node/lib/node_modules/serverless/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'region' of undefined
    at ServerlessCors.addPreflightRequests (/User/X/Code/chatter/node_modules/serverless-cors-plugin/src/index.js:68:29)
From previous event:
    at /User/X/.node/lib/node_modules/serverless/lib/Serverless.js:177:25
    at Array.reduce (native)
    at Serverless._execute (/User/X/.node/lib/node_modules/serverless/lib/Serverless.js:176:26)
    at Object.actions.(anonymous function) [as endpointDeploy] (/User/X/.node/lib/node_modules/serverless/lib/Serverless.js:378:20)
    at /User/X/.node/lib/node_modules/serverless/lib/actions/DashDeploy.js:288:34
From previous event:
    at DashDeploy._deploy (/User/X/.node/lib/node_modules/serverless/lib/actions/DashDeploy.js:283:10)
From previous event:
    at DashDeploy.dashDeploy (/User/X/.node/lib/node_modules/serverless/lib/actions/DashDeploy.js:132:10)
From previous event:
    at /User/X/.node/lib/node_modules/serverless/lib/Serverless.js:152:29
    at Array.reduce (native)
    at /User/X/.node/lib/node_modules/serverless/lib/Serverless.js:151:30
    at processImmediate [as _immediateCallback] (timers.js:384:17)
From previous event:
    at Serverless._execute (/User/X/.node/lib/node_modules/serverless/lib/Serverless.js:149:10)
    at Serverless.actions.(anonymous function) (/User/X/.node/lib/node_modules/serverless/lib/Serverless.js:378:20)
    at Serverless.command (/User/X/.node/lib/node_modules/serverless/lib/Serverless.js:347:38)
    at Object.<anonymous> (/User/X/.node/lib/node_modules/serverless/bin/serverless:16:12)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

**Comment by joostfarla** [comment]
Thanx for reporting! I'll be releasing a new version of the plugin in a few days!

**Comment by joostfarla** [comment]
The plugin is now compatible with the brand new release of Serverless (v0.2)!

**Comment by edclement** [comment]
Thanks for updating this!
